```{r, echo=FALSE}
HIDDEN_SOLS=FALSE
set.seed(15732)
ggplot2::theme_set(ggplot2::theme_gray(base_size=13))
```

# Inferences from two independent samples {#two-indep-samples}


<div class="lo">
#### Instructions {-}
  
  - In this two-hour lab we will go through worked examples in the first hour, and you will attempt to answer some questions in the second hour.
- The Rmarkdown file for this week is [here](https://uoe-psychology.github.io/uoe_psystats/dapr1/labsheets/week_15_practice.Rmd).


#### Learning outcomes {-}

**LO1.** Understand how to perform a two-sample t-test and interpret the results.

**LO2.** Understand how to calculate a two-sample t-interval and interpret the results.

**LO3.** Being able to check the technical conditions for applying the t-procedures.

</div>


## Recap

- ???

- ???



## Walkthrough


### Example 1: When you call my name...

Can a waitress earn higher tips simply by giving her name when she greets her customers?


[Garrity & Degelman (1990)](#w17-references) investigated if waitresses can increase their tips simply by introducing themselves by name when greeting customers.
The two researchers 


### Example 1: Does color affect creativity and cognitive tasks? {-}

Researchers [Mehta & Zhu (2009)](#w17-references) reported an interesting study evaluating the effect of color on cognitive tasks and creativity.

The two researchers randomly allocated subjects to either a room with a red or blue background.
All subjects were asked to generate as many creative uses for a brick as they could think of within 1 minute.
The quality of their responses was scored by a panel of judges, leading to the following scores of creativity:

|                 |                                        |
|:----------------|:--------------------------------------:|
| Red background  | $n = 35$, $\bar{x} = 3.39$, $s = 0.97$ |
| Blue background | $n = 36$, $\bar{x} = 3.97$, $s = 0.63$ |

Table: **Creativity scores**



<!-- |                 |                                         | -->
<!-- |:----------------|:---------------------------------------:| -->
<!-- | Red background  | $n = 35$, $\bar{x} = 15.89$, $s = 5.90$ | -->
<!-- | Blue background | $n = 36$, $\bar{x} = 12.31$, $s = 5.48$ | -->

<!-- Table: **Accuracy scores** -->

The researcher's claim is that "blue enhances performance on creative tasks".


We note that

1. the values of the two population standard deviations are not known
2. the two samples are independent
3. the samples are simple random samples
4. satisfied the condition that both samples should have size > 30 or that they come from populations having normal distributions


__Step 1. Convert the claim of interest to two competing hypotheses__

The claim is that "blue enhances performance on creative tasks". 
This can be equivalently stated as: people with a blue background will score on average higher than people with a red background.


$$
H_0 : \mu_R \geq \mu_B \\
H_1 : \mu_R < \mu_B
$$


### Case 1: Independent samples with $\sigma_1$ and $\sigma_2$ known {-#two-indep-samples-case-1}

In this section we deal with the scenario when we are testing hypotheses about the means of two populations, $\mu_1$ and $\mu_2$.
The two available samples, one from each population, are assumed to be independent.
Furthemore, we assume we know the standard deviation of the two populations, $\sigma_1$ and $\sigma_2$.


<div class="red">
#### Requirements {-}

1. Distribution of the population. Either or both:
  + The two samples come from populations which are normally distributed;
  + The two sample sizes are both large: $n_1 > 30$ and $n_2 > 30$.

2. The two samples are _independent._

3. Both samples are _simple random samples._


</div>


---


### Example 2: {-}


### Case 2: Independent samples with $\sigma_1$ and $\sigma_2$ unknown and equal {-#two-indep-samples-case-2}



---



### Example 3: {-}


### Case 3: Independent samples with $\sigma_1$ and $\sigma_2$ unknown and not equal {-#two-indep-samples-case-3}




## References {#w17-references}

- Garrity, K., & Degelman, D. (1990). Effect of server introduction on restaurant tipping 1. Journal of Applied Social Psychology, 20(2), 168-172.
- Mehta, R., & Zhu, R. J. (2009). Blue or red? Exploring the effect of color on cognitive task performances. Science, 323(5918), 1226-1229.


