```{r, echo=FALSE}
HIDDEN_SOLS=FALSE
set.seed(15732)
ggplot2::theme_set(ggplot2::theme_gray(base_size=13))

library(tidyverse)
```

# Normal distributions & probability {#chap-normal}


<div class="lo">
#### Instructions {-}
  
- In this two-hour lab we will go through worked examples in the first hour, and you will attempt to answer some questions in the second hour.
- The Rmarkdown file for this week is [here](https://uoe-psychology.github.io/uoe_psystats/dapr1/labsheets/week_14_practice.Rmd).


#### Learning outcomes {-}

**LO1.** Understand the different types of errors 

**LO2.** Introduce statistical power  

**LO3.** Conduct basic power analysis 

#### Reading {-}

?????????????????????

</div>


## Recap


1. random chance
1. alternative explanation
1. statistical hypothesis HoHa!
1. from random chance model, we constructed a null distribution.(lab involved bootstrapping the null)
1. compare observed statistic to null distribution
1. retrieved p-value (proportion of null distribution at least as extreme as observed)
1. made a formal decision.


## Walkthrough


hypothetical - research q: 
our null is that 
our alternaitve is 

plot hypothetical null.
plot observed
p-value <.05

conclusion - hooray, !

BUT have we made an mistake here? 
raise hands if believe H_a (hopefully only few) 

this is like: 
convicting an innocent person


option... decrease alpha!
div think - what are we doing here? we making the probability of convicting an innocent person much less likely 
casually - we've got to get some *really strong evidence* that they're guilty. 

## the flip side

on the other hand...
research Q: is global temperature rising? 
H_o, temperature in y1 == temperature y2
H_a temperature in y1 != temperature y2
do a test, 
get a p-value <.01
with our new alpha of .001, we don't reject H_o. 
But maybe we're being to strict! 
Now we are letting a guilty person walk free!


### table of conviction

### table of errors 
alpha, beta


Q what are our ideal values for alpha nad beta? 
A 0 and 0. 
BUT, this isn't possible when we sample



## 

### In-class activity





---

## Lab



