```{r, echo=FALSE}
HIDDEN_SOLS=TRUE
set.seed(15732)
ggplot2::theme_set(ggplot2::theme_gray(base_size=13))

library(tidyverse)
```

# One Sample Mean Test {#chap-one-mean-test}


<div class="lo">
#### Instructions {-}
  
- In this two-hour lab we will go through worked examples in the first hour, and you will attempt to answer some questions in the second hour.
- The Rmarkdown file for this week is [here](https://uoe-psychology.github.io/uoe_psystats/dapr1/labsheets/week_16_practice.Rmd).


#### Learning outcomes {-}

**LO1.** 

**LO2.** 

**LO3.** 

<!-- #### Reading {-} -->

</div>

## paired t-test  


### Example questions {-}


### Hypotheses {-}  


• The null hypothesis (H0) assumes that the true mean difference (μd) is equal to zero.
• The two-tailed alternative hypothesis (H1) assumes that μd is not equal to zero.
• The upper-tailed alternative hypothesis (H1) assumes that μd is greater than zero.
• The lower-tailed alternative hypothesis (H1) assumes that μd is less than zero.
The mathematical representations of the null and alternative hypotheses are defined below:

H0: μd = 0
H1: μd ≠ 0    (two-tailed)
H1: μd > 0    (upper-tailed)
H1: μd < 0    (lower-tailed)


**Null hypothesis:**  


**Alternative hypothesis:** 


### Paired data  

*pairs of time points*
Longitudinal Variables: Same person, same variable, different times

*pairs of variables*
Within-Person Contrast: Same person, different variables

*pairs of people*
Dyadic Data: Same variable, different people

### Formula {-}  

start with t statistic formula.


https://www.statisticssolutions.com/manova-analysis-paired-sample-t-test/

The procedure for a paired sample t-test can be summed up in four steps. The symbols to be used are defined below:

$D$ = Differences between two paired samples
$d_i$ = The ith observation in D
$n$ = The sample size
$\bar{d}$ = The sample mean of the differences
$s_d$ = The sample standard deviation of the differences
$T$ =The critical value of a t-distribution with (n − 1) degrees of freedom
$t$ = The t-statistic (t-test statistic) for a paired sample t-test
$p$ = The p-value (probability value) for the t-statistic.
The four steps are listed below:

1. Calculate the sample mean.
Undefined control sequence \cfrac
2. Calculate the sample standard deviation.
Undefined control sequence \cfrac
3. Calculate the test statistic.
Undefined control sequence \cfrac
4. Calculate the probability of observing the test statistic under the null hypothesis. This value is obtained by comparing t to a t-distribution with (n − 1) degrees of freedom. This can be done by looking up the value in a table, such as those found in many statistical textbooks, or with statistical software for more accurate results.
p = 2 ⋅ Pr(T > |t|)    (two-tailed)
p = Pr(T > t)    (upper-tailed)
p = Pr(T < t)    (lower-tailed)
determine whether the results provide sufficient evidence to reject the null hypothesis in favor of the alternative hypothesis.




## Walkthrough 


- scores on ACE-III 
The Addenbrooke's Cognitive Examination-III (ACE-III) is a brief cognitive test that assesses five cognitive domains: attention, memory, verbal fluency, language and visuospatial abilities. ... The total score is 100 with higher scores indicating better cognitive functioning

q - how is the data paired?
a - same person, same variable, different time points

q hypotheses?

q - make a new column of the difference in scores between time points  
a - mutate(diff = t2-t1)

q - calculate $\bar{x}_d$ and $s_d$.  
a - summarise(mean(diff), sd(diff))

q - fill in blanks t-statistic 

q - calculate t in r

q - calculate pr(t)  

q - how would we report this? t(df) = , p </>/= ?


## ALL IN ONE LINE OF CODE! {-}

q - run ?t.test. what might be the argument we need to use for this test?  
a - paired = TRUE  


## Assumptions {-}  

 The dependent variable must be continuous (interval/ratio).
• The observations are independent of one another.
• The dependent variable should be approximately normally distributed.
• The dependent variable should not contain any outliers.


## Summary  



## Lab  
  
_Please attempt the questions **before** looking at the solutions. Copy & pasting the solutions will not help with learning!_  



data - happiness in romantic relationships men v women

data - school students preference for math vs preference for english















### Glossary  
